### ISSUE TITLE
Libri

### ISSUE THREAD

**Issue by AbateSimone** [OmarFacchini/ChatCom#3]
Incomincia a fare un po di documentazione, casi d'uso ed una spiegazione dell'applicazione.

**Comment by demetrio1234523** [comment]
non conviene che aspetto che finiate  così non mi modificate tutto? per tutto intendo le cose già scritte nelle idee .

**Comment by AbateSimone** [comment]
Libri invece che nel documentation txt puoi meterli nel readme, ciò permette di vederlo anche nella parte sottostante
